name: ecommerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  backdrop: ^0.7.1
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  card_swiper: ^2.0.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_staggered_grid_view: ^0.6.1
  google_sign_in: ^5.2.4
  image_picker: ^0.8.4+9
  list_tile_switch: ^1.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  uuid: ^3.0.6
  wave: ^0.2.0
  http: ^0.13.4
  flutter_stripe: ^2.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
